CREATE TABLE QUESTIONS(ID INT PRIMARY KEY, QUESTION VARCHAR(255), DIFFICULTY INT);
ALTER TABLE QUESTIONS ALTER COLUMN ID INT AUTO_INCREMENT;
"INSERT INTO QUESTIONS (ID,QUESTION,DIFFICULTY) VALUES (?,?, ?)";
"UPDATE QUESTIONS SET QUESTION=?,DIFFICULTY=? WHERE ID=?";
"DELETE QUESTIONS WHERE ID=?";
"SELECT QUESTION,ID,DIFFICULTY FROM QUESTIONS WHERE (? IS NOT NULL AND QUESTION LIKE ?) AND (? IS NOT NULL  AND DIFFICULTY = ?)";
"select ID,QUESTION,DIFFICULTY,ANSWER from QUESTIONS ,ANSWERS  where QUESTIONS.ID=ANSWERS.Q_ID";

